name: Build nodejs application

on:
  workflow_dispatch:

jobs:
  container-save-two-cpu:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      options: --cpus 2
      env:
        CACHE_NAME: "cpu-two"
    steps:
      - run: |
          apk update
          apk add git>=2.18 tar
      - uses: actions/checkout@v3

      - run: npm ci --force

      - uses: actions/cache/save@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json', 'yarn.lock') }}-${{ env.CACHE_NAME }}

      - run: ls -la && exit 1

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: my-artifact
          path: runner-diagnostic-logs/

  container-save-without-cpu-tune:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      env:
        CACHE_NAME: "cpu-one"
    steps:
      - run: |
          apk update
          apk add git>=2.18 tar
      - uses: actions/checkout@v3

      - run: npm ci --force

      - uses: actions/cache/save@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json', 'yarn.lock') }}-${{ env.CACHE_NAME }}

  without-container:
    runs-on: ubuntu-latest
    env:
      CACHE_NAME: "without"
    steps:
      - uses: actions/checkout@v3

      - run: npm ci --force

      - uses: actions/cache/save@v3
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json', 'yarn.lock') }}-${{ env.CACHE_NAME }}

